### ISSUE TITLE
Avoid third-party urls for CX packages.

### ISSUE THREAD

**Issue by Gcenx** [marzent/ffxiv-on-mac#1]
https://github.com/marzent/ffxiv-on-mac/blob/6163e61511b0e98dc7ca2c9be8902d38732c9db4/install.sh#L58

All publicly available CX releases can be downloaded from the following url
```
https://media.codeweavers.com/pub/crossover/cxmac/demo/
```
All CrossOver packages are considered a “demo” until activated.

**Comment by seathasky** [comment]
good idea tbh, thanks for the heads up

**Comment by marzent** [comment]
Oh good to know, thought you needed to be logged in to download old versions

**Comment by Gcenx** [comment]
> Oh good to know, thought you needed to be logged in to download old versions

Whats shown when your logged in is versions you have a license for.

Nightly/Beta and require a login, also special circumstances (a port/patch data etc) is behind urls that require a provided password that’s not the same as your account and can only be provided by the employee who generated the link.

**Comment by seathasky** [comment]
Aight fixed it. honestly though, me and marzent didnt know that existed

**Comment by marzent** [comment]
fixed with efde0735f4ec4c522b5f97e441ecbf80cd5acfaf
